"""initial

Revision ID: 17c3a32ec8ac
Revises: 
Create Date: 2023-03-02 18:06:31.247224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17c3a32ec8ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis')
    op.drop_table('users')
    op.drop_table('orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('ord_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ord_datetime', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('ord_an', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('ord_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ord_an'], ['analysis.an_id'], name='fk_orders', onupdate='CASCADE', ondelete='CASCADE')
    )
    op.create_table('users',
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('nickname', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('date_birth_day', sa.DATE(), autoincrement=False, nullable=True)
    )
    op.create_table('analysis',
    sa.Column('an_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('an_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('an_cost', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('an_price', sa.REAL(), autoincrement=False, nullable=True),
    sa.UniqueConstraint('an_id', name='analysis_an_id_key')
    )
    # ### end Alembic commands ###
